### ISSUE TITLE
Would be great to have an alias devices -> servers

### ISSUE THREAD

**Issue by dmitryshagin** [fog/fog-packet#24] opened 2018-08-30 12:57 UTC
As for now I have either monkeypatch Packet in order to have an access to `compute.servers` instead of `compute.devices` or change my code later to communicate to packet in a different way (we support different server providers and Packet is the only one with `devices` instead on more common `servers`.

**Comment by edevenport** [comment] 2018-08-30 16:18
@jasmingacic - This crossed my mind as well. The standardize model across providers is named `server` vs `device`. Since the Fog framework should allow replacing providers with minimal or no changes, we should provide the same model name as @dmitryshagin describes.

I would recommend we name `device` and `devices` to `server` and `servers`. Then create a new `device` model (and collection) which inherits the server model. I think this should allow us to maintain a single model, but referenced either way?

**Comment by edevenport** [comment] 2018-09-04 12:11
@dmitryshagin We have merged the proposed change into master. Would you be able to [build the module](https://github.com/fog/fog-packet#build) from master and confirm it behaves as expected? Once this and the other latest changes are confirmed, we can tag a release.

**Comment by dmitryshagin** [comment] 2018-09-04 12:30
Thanks. Will check and report. Probably later this week.

**Comment by dmitryshagin** [comment] 2018-09-12 07:25
LGTM, thanks.

**Closed** 2018-09-12 10:01 UTC
